Repository rapid7/metasploit-payloads, pull requests merged in 2020-09, with the labels that each got.

#427 Add proxy authentication support to the Python Meterpreter
  python/meterpreter/meterpreter.py
Labels: python

#431 GetSystem Technique #4 (Named Pipe Impersonation RPCSS Variant)
  c/meterpreter/source/extensions/priv/elevate.c
  c/meterpreter/source/extensions/priv/elevate.h
  c/meterpreter/source/extensions/priv/namedpipe.c
  c/meterpreter/source/extensions/priv/namedpipe.h
  c/meterpreter/source/extensions/priv/namedpipe_rpcss.c
  c/meterpreter/source/extensions/priv/namedpipe_rpcss.h
  c/meterpreter/workspace/ext_server_priv/ext_server_priv.vcxproj
Labels: feature, windows

#432 Add SECURITY.md
  .github/SECURITY.md
Labels: easy, enhancement
