Repository rapid7/metasploit-payloads, pull requests merged in 2020-10, with the labels that each got.

#437 Fix Metasploit 6 pivoting issue
  c/meterpreter/source/common/common_command_ids.h
  c/meterpreter/source/metsrv/server_pivot_named_pipe.c
Labels: bug

#438 Disconnect the named pipe and break after the impersonation callback
  c/meterpreter/source/extensions/priv/namedpipe.c
Labels: bug, windows

#443 Revert "Undo commit for #441" (revert the revert of the merge that was correct to begin with)
  .github/SECURITY.md
  c/meterpreter/source/common/common_command_ids.h
  c/meterpreter/source/extensions/priv/elevate.c
  c/meterpreter/source/extensions/priv/elevate.h
  c/meterpreter/source/extensions/priv/namedpipe.c
  c/meterpreter/source/extensions/priv/namedpipe.h
  c/meterpreter/source/extensions/priv/namedpipe_rpcss.c
  c/meterpreter/source/extensions/priv/namedpipe_rpcss.h
  c/meterpreter/source/metsrv/server_pivot_named_pipe.c
  c/meterpreter/workspace/ext_server_priv/ext_server_priv.vcxproj
  php/meterpreter/meterpreter.php
  python/meterpreter/meterpreter.py
Labels: bug

#435 Update makefile to match new output folder and naming convention.
  Makefile
Labels: bug, easy, windows
