Repository rapid7/metasploit-payloads, pull requests merged in 2023-06, with the labels that each got.

#637 Always warn when using custom meterpreter dependencies
  gem/lib/metasploit-payloads.rb
Labels: enhancement

#648 Add update_token function to stdapi
  c/meterpreter/source/common/common_command_ids.h
  c/meterpreter/source/extensions/stdapi/server/stdapi.c
  c/meterpreter/source/extensions/stdapi/server/sys/config/config.c
  c/meterpreter/source/extensions/stdapi/server/sys/config/config.h
Labels: windows

#656 Fix double-free in free
  c/meterpreter/source/extensions/stdapi/server/sys/process/memory.c
Labels: bug, windows

#660 Fix PPID spoofing
  c/meterpreter/source/extensions/stdapi/server/sys/process/process.c
Labels: bug, windows

#662 fix bug where env lookups not found return garbage
  c/meterpreter/source/extensions/stdapi/server/sys/config/config.c
Labels: bug, windows

#663 Fix python meterpreter getuid crash on windows
  python/meterpreter/README.md
  python/meterpreter/ext_server_stdapi.py
  python/meterpreter/tests/test_ext_server_stdapi.py
Labels: bug, python
